spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/visangfront
    username: visang
    password: visang123@
  mustache:
    prefix: classpath:/templates/
    suffix: .mustache
    check-template-location: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.visang.front.b2b.user.domain
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 9990

logging:
  level:
    com.visang.front: DEBUG